-- ============================================================
-- FLUX — Seed Candidates (run AFTER supabase-schema.sql)
-- 50+ realistic fictional candidates from Indian product &
-- logistics companies covering all iimjobs/naukri fields
-- ============================================================

INSERT INTO candidates (
  full_name, email, phone, gender,
  current_role, current_company, company_type, industry, functional_area,
  total_experience, experience_years, previous_companies,
  current_ctc, current_ctc_numeric, expected_ctc, expected_ctc_numeric,
  notice_period, notice_period_days,
  current_location, preferred_location, wfh_preference, willing_to_relocate,
  highest_qualification, college, graduation_year, tier,
  key_skills, profile_summary,
  ai_comfort_score, ai_tools_used, ai_project_built,
  ai_future_vision, ai_without_tools_feeling, biggest_build, why_us,
  linkedin_url, github_url,
  score, score_breakdown, status, source
) VALUES

-- ============================================================
-- PRODUCT COMPANIES
-- ============================================================

(
  'Arjun Mehta', 'arjun.mehta@gmail.com', '9876543210', 'Male',
  'Senior Product Manager', 'Razorpay', 'product', 'Fintech', 'Product Management',
  '6 years 2 months', 6.2, 'Paytm, Ola',
  '28 LPA', 28, '40 LPA', 40,
  '2 months', 60,
  'Bengaluru', 'Bengaluru / Remote', 'hybrid', false,
  'B.Tech', 'IIT Bombay', '2018', 'Tier 1',
  'Product Strategy, Payments, API Design, Growth, SQL, Figma, A/B Testing',
  '6+ years PM with deep fintech expertise. Led payments infrastructure at Razorpay serving 2M+ merchants. Strong analytical background with IIT pedigree.',
  '9', 'Claude for PRDs, Cursor for light scripting, Notion AI, custom GPT for competitor analysis',
  'Built internal AI triage tool classifying 10k+ monthly support tickets with 89% accuracy. Cut L1 response time 60%.',
  'Redesign discovery using AI — synthetic user testing, auto hypothesis trees, before a single sprint starts.',
  'Devastated. My entire workflow is AI-first. 40% slower minimum.',
  'Led payments infra migration at Razorpay — 3 legacy systems into one unified API, 2M+ merchants, zero downtime.',
  'Shiprocket is at an AI inflection point in logistics. I want to be in the room.',
  'https://linkedin.com/in/arjunmehta-pm', 'https://github.com/arjunm',
  88, '{"ai_depth": 23, "communication": 22, "experience_relevance": 23, "ambition": 20, "total": 88, "summary": "Exceptional AI depth with real shipped impact. Strong PM instincts and IIT pedigree."}',
  'shortlisted', 'form'
),

(
  'Priya Sharma', 'priya.sharma@gmail.com', '9845678901', 'Female',
  'Data Scientist', 'Flipkart', 'product', 'E-commerce', 'Data Science & Analytics',
  '4 years', 4, 'Mu Sigma',
  '22 LPA', 22, '32 LPA', 32,
  '1 month', 30,
  'Bengaluru', 'Bengaluru', 'hybrid', false,
  'M.Tech', 'IIT Delhi', '2020', 'Tier 1',
  'Python, Machine Learning, SQL, LangChain, PyTorch, Feature Engineering, A/B Testing, Spark',
  'Data scientist with 4 years building ML systems at scale. Led demand forecasting and pricing models at Flipkart fashion vertical.',
  '8', 'Claude API for pipelines, Jupyter + Copilot, LangChain for RAG, W&B',
  'Real-time demand forecasting using LLM-assisted feature engineering. 18% accuracy improvement, saved ₹4Cr in inventory.',
  'Auto-EDA, automated insight generation, 3x faster shipping.',
  'Uncomfortable but I would adapt. Grew up writing from scratch.',
  'End-to-end ML platform for Flipkart fashion — feature store, model registry, auto-retraining. 8M SKUs.',
  'Scale of logistics data at Shiprocket is exactly what I want to work on.',
  'https://linkedin.com/in/priyasharma-ds', 'https://github.com/priya-ml',
  82, '{"ai_depth": 21, "communication": 20, "experience_relevance": 22, "ambition": 19, "total": 82, "summary": "Strong ML engineering with proven impact. Clear thinking on logistics applications."}',
  'new', 'form'
),

(
  'Rohan Kapoor', 'rohan.kapoor@gmail.com', '9901234567', 'Male',
  'Engineering Manager', 'Swiggy', 'product', 'Food Delivery', 'Technology',
  '8 years', 8, 'Microsoft, Walmart Labs',
  '45 LPA', 45, '60 LPA', 60,
  '3 months', 90,
  'Bengaluru', 'Bengaluru', 'hybrid', false,
  'B.Tech', 'BITS Pilani', '2016', 'Tier 1',
  'Java, Distributed Systems, System Design, Kafka, Redis, Team Leadership, Go',
  'Engineering leader with 8 years experience. Scaled Swiggy order assignment engine from 10k to 2M orders/day. Led team of 18 across 3 squads.',
  '7', 'GitHub Copilot, Claude for design docs and code reviews, Linear AI',
  'AI-assisted code review bot integrated into CI — flags anti-patterns, security issues, performance bottlenecks.',
  'AI design docs, automated tests, AI reviews. Human time for architecture and culture.',
  'Frustrated. Remember before-times. Would slow down not stop.',
  'Built and scaled Swiggy real-time order assignment engine, 10k to 2M orders/day.',
  'Want logistics-scale infrastructure problems. Swiggy is solved. Shiprocket is next.',
  'https://linkedin.com/in/rohankapoor-eng', '',
  75, '{"ai_depth": 18, "communication": 19, "experience_relevance": 21, "ambition": 17, "total": 75, "summary": "Solid engineering leader with real scale. AI integration practical and thoughtful."}',
  'new', 'form'
),

(
  'Sneha Reddy', 'sneha.reddy@gmail.com', '9988776655', 'Female',
  'Growth Manager', 'Meesho', 'product', 'Social Commerce', 'Marketing & Growth',
  '3 years 6 months', 3.5, 'Housing.com',
  '16 LPA', 16, '24 LPA', 24,
  'Immediate', 0,
  'Hyderabad', 'Remote / Bengaluru', 'remote', true,
  'MBA', 'IIM Ahmedabad', '2021', 'Tier 1',
  'Growth Hacking, SQL, Python, Amplitude, CleverTap, WhatsApp Marketing, Referral Programs',
  'Growth manager with deep B2C expertise. Built Meesho reseller acquisition programs scaling to 400k active users.',
  '9', 'Claude for campaigns and A/B analysis, Perplexity, Make.com + AI automation, Canva AI',
  'Automated WhatsApp campaign system with AI-personalised messages for Meesho resellers. 3x CTR vs generic blasts.',
  '10x more experiments. Hypothesis to launched test in hours not days.',
  'Like losing a superpower. Fully rebuilt workflow around AI.',
  'Zero to 400k active resellers — referral program that became top acquisition channel for 2 quarters.',
  'AI-native growth playbook in logistics is wide open. Nobody has done it.',
  'https://linkedin.com/in/snehareddy-growth', '',
  79, '{"ai_depth": 22, "communication": 20, "experience_relevance": 18, "ambition": 19, "total": 79, "summary": "High AI fluency with creative growth applications. Strong self-starter."}',
  'interview', 'form'
),

(
  'Aditya Bose', 'aditya.bose@gmail.com', '9432109876', 'Male',
  'Founding Engineer', 'Stealth Startup', 'startup', 'SaaS', 'Technology',
  '7 years', 7, 'Freshworks, ThoughtWorks',
  '35 LPA', 35, '50 LPA', 50,
  'Immediate', 0,
  'Bengaluru', 'Anywhere', 'remote', true,
  'B.Tech', 'NIT Trichy', '2017', 'Tier 1',
  'Node.js, Python, LangChain, LangGraph, Claude API, RAG, System Design, Stripe, AWS',
  'Full-stack AI engineer. Built and sold AI-native B2B SaaS. Deep Claude API expertise with custom agents and multi-step workflows.',
  '10', 'Claude API (custom agents, RAG, LangGraph), Cursor, v0 for UI, fine-tuned models',
  'AI-native contract review SaaS — Claude-powered, RAG over legal docs, Stripe billing, SOC2 prep. $12k MRR, 40 customers.',
  'Rebuild every internal workflow. AI agents for data pipelines, anomaly detection, self-healing infra.',
  'Like asking a surgeon to operate with chopsticks.',
  'Full-stack AI platform solo in 6 months — Claude integration, RAG, billing, compliance.',
  'Shiprocket has data, infrastructure complexity, and GTM moat. I want to be patient zero for AI adoption.',
  'https://linkedin.com/in/adityabose-eng', 'https://github.com/adityab',
  96, '{"ai_depth": 25, "communication": 24, "experience_relevance": 24, "ambition": 23, "total": 96, "summary": "Rare combination of deep AI engineering and product thinking. Has shipped real AI products. Top priority."}',
  'offer', 'form'
),

(
  'Ananya Iyer', 'ananya.iyer@gmail.com', '9765432109', 'Female',
  'UX Designer', 'CRED', 'product', 'Fintech', 'Design',
  '4 years', 4, 'Razorpay',
  '20 LPA', 20, '28 LPA', 28,
  '1 month', 30,
  'Mumbai', 'Remote', 'remote', true,
  'B.Des', 'NID Ahmedabad', '2020', 'Tier 1',
  'Figma, UX Research, Prototyping, Design Systems, Motion Design, Accessibility, Usability Testing',
  'Product designer with 4 years crafting fintech experiences. Led design system at CRED used by 30+ designers.',
  '8', 'Figma AI, Midjourney, Claude for UX writing and research synthesis, Maze AI',
  'Redesigned CRED rewards discovery using AI-synthesised 200+ interview transcripts. 35% increase in redemption rate.',
  'AI removes grunt work from research. 50 interviews synthesised in an hour. More designing, less transcribing.',
  'Very uncomfortable. AI fundamentally changed how fast I validate ideas.',
  'Full design system for CRED from scratch — 400+ components, motion guidelines, accessibility standards.',
  'Fintech UX is solved. Logistics UX is still a disaster. 10x more impact.',
  'https://linkedin.com/in/ananyaiyer-ux', '',
  77, '{"ai_depth": 20, "communication": 21, "experience_relevance": 17, "ambition": 19, "total": 77, "summary": "Impressive AI fluency for a designer. Would bring AI-native thinking to product design."}',
  'shortlisted', 'form'
),

(
  'Kabir Singh', 'kabir.singh@gmail.com', '9123456789', 'Male',
  'Backend Engineer', 'PhonePe', 'product', 'Fintech', 'Technology',
  '5 years', 5, 'Infosys',
  '30 LPA', 30, '42 LPA', 42,
  '2 months', 60,
  'Pune', 'Bengaluru / Remote', 'hybrid', true,
  'B.Tech', 'VIT Vellore', '2019', 'Tier 2',
  'Java, Spring Boot, Kafka, PostgreSQL, Redis, Microservices, AWS, Docker, Kubernetes',
  'Backend engineer specialising in high-throughput payment systems. Built transaction reconciliation handling ₹50Cr daily.',
  '6', 'GitHub Copilot daily, Claude for documentation, ChatGPT for debugging',
  'Used AI pair programming to refactor 15-year-old payment module. 40% complexity reduction, 30% to 85% test coverage.',
  'Faster delivery, better test coverage, cleaner docs. Force multiplier for ICs.',
  'Slower but manageable. Learned coding without AI.',
  'Transaction reconciliation system at PhonePe — ₹50Cr daily, 99.99% accuracy.',
  'Software moving money is interesting. Software moving boxes at scale feels more tangible.',
  'https://linkedin.com/in/kabirsingh-be', 'https://github.com/kabirs',
  62, '{"ai_depth": 14, "communication": 16, "experience_relevance": 17, "ambition": 15, "total": 62, "summary": "Solid backend engineering. AI usage functional but not deeply integrated. Good potential."}',
  'new', 'form'
),

(
  'Divya Menon', 'divya.menon@gmail.com', '9543210987', 'Female',
  'Product Analyst', 'Amazon', 'product', 'E-commerce', 'Data Science & Analytics',
  '3 years', 3, 'Fractal Analytics',
  '18 LPA', 18, '26 LPA', 26,
  '1 month', 30,
  'Bengaluru', 'Bengaluru', 'hybrid', false,
  'MBA', 'XLRI Jamshedpur', '2021', 'Tier 1',
  'SQL, Python, Tableau, dbt, Mixpanel, Product Analytics, Funnel Analysis, Cohort Analysis',
  'Product analyst bridging data and product decisions. Built analytics frameworks used org-wide at Amazon India.',
  '7', 'Claude for SQL generation, dbt + AI, Hex AI for insights',
  'AI-assisted funnel analysis tool auto-generating insight summaries from raw event data. Used by 12 PMs at Amazon India.',
  'Automate reporting layer entirely. 100% time on forward-looking analysis.',
  'Frustrated but functional. Speed is the main loss.',
  'Redesigned Amazon India seller onboarding metrics framework — new definitions, new dashboards, adopted org-wide.',
  'Want to own 1% of outcomes not 0.001%. Shiprocket analytics is greenfield.',
  'https://linkedin.com/in/divyamenon-data', 'https://github.com/divyam',
  71, '{"ai_depth": 17, "communication": 18, "experience_relevance": 19, "ambition": 17, "total": 71, "summary": "Strong analytical background. Good self-awareness. Solid candidate for analytics roles."}',
  'new', 'form'
),

(
  'Rahul Joshi', 'rahul.joshi@gmail.com', '9712345678', 'Male',
  'Associate Product Manager', 'Zomato', 'product', 'Food Delivery', 'Product Management',
  '2 years', 2, 'Deloitte',
  '14 LPA', 14, '20 LPA', 20,
  '1 month', 30,
  'Gurugram', 'Delhi NCR / Bengaluru', 'hybrid', true,
  'MBA', 'IIM Calcutta', '2022', 'Tier 1',
  'Product Roadmap, User Research, SQL, Wireframing, Competitive Analysis, Agile, JIRA',
  'APM at Zomato owning restaurant discovery and search. Strong IIM background with consulting foundation.',
  '7', 'Claude for PRDs and user stories, ChatGPT for research, Notion AI',
  'Built AI-powered restaurant recommendation carousel improving CTR by 22% on homepage.',
  'AI to run continuous experimentation. Test 10 features per week instead of 2.',
  'Slower but manageable. AI is still fairly new to my workflow.',
  'Led restaurant discoverability revamp at Zomato — new search algorithm, 8% GMV uplift.',
  'Want to work on harder logistics problems. Zomato search is done. Shiprocket routing is not.',
  'https://linkedin.com/in/rahuljoshi-pm', '',
  68, '{"ai_depth": 16, "communication": 18, "experience_relevance": 17, "ambition": 17, "total": 68, "summary": "Promising early-career PM with good instincts. AI integration is growing. Strong pedigree."}',
  'new', 'form'
),

(
  'Nidhi Agarwal', 'nidhi.agarwal@gmail.com', '9634567890', 'Female',
  'Senior Software Engineer', 'Paytm', 'product', 'Fintech', 'Technology',
  '5 years 4 months', 5.3, 'HCL Technologies',
  '24 LPA', 24, '36 LPA', 36,
  '2 months', 60,
  'Noida', 'Delhi NCR / Remote', 'remote', true,
  'B.Tech', 'DTU Delhi', '2019', 'Tier 2',
  'Python, Django, REST APIs, PostgreSQL, Redis, Docker, AWS, CI/CD, React',
  'Full-stack engineer at Paytm payments. Strong Python backend with growing frontend capabilities.',
  '7', 'GitHub Copilot, Claude for API documentation and code review, Tabnine',
  'Built Paytm merchant onboarding API automation using AI-generated test cases. Reduced manual QA by 70%.',
  'AI handles boilerplate. I focus on architecture and edge cases. 2x throughput.',
  'Would miss it but have strong fundamentals.',
  'Designed merchant KYC automation pipeline at Paytm — 50k+ merchants onboarded monthly.',
  'Want to work in a company where engineering decisions matter and move fast.',
  'https://linkedin.com/in/nidhiagarwal-eng', 'https://github.com/nidhi-dev',
  69, '{"ai_depth": 17, "communication": 17, "experience_relevance": 18, "ambition": 17, "total": 69, "summary": "Solid engineer with practical AI integration. Good potential for logistics tech roles."}',
  'new', 'form'
),

(
  'Siddharth Kulkarni', 'siddharth.k@gmail.com', '9556789012', 'Male',
  'Head of Marketing', 'UrbanCompany', 'product', 'Home Services', 'Marketing & Growth',
  '10 years', 10, 'Myntra, Jabong, MakeMyTrip',
  '55 LPA', 55, '75 LPA', 75,
  '3 months', 90,
  'Bengaluru', 'Bengaluru', 'hybrid', false,
  'MBA', 'IIM Bangalore', '2014', 'Tier 1',
  'Brand Marketing, Performance Marketing, Growth, P&L, Team Leadership, CRM, MarTech',
  'Marketing leader with 10 years at India internet cos. Scaled UrbanCompany brand to ₹500Cr GMV. Expert in AI-assisted campaign management.',
  '8', 'Claude for campaign strategy and copy, Jasper, Perplexity, HubSpot AI',
  'AI-driven personalisation engine for UrbanCompany re-engagement. 28% improvement in repeat booking rate.',
  'AI marketing operating system — automated creative testing, AI budget allocation, real-time optimisation.',
  'A step back to 2019. Operational but slower.',
  'Built UrbanCompany from ₹100Cr to ₹500Cr GMV over 3 years. Team of 25.',
  'Logistics marketing is an untapped category. No one is doing brand-building at Shiprocket scale.',
  'https://linkedin.com/in/siddharthkulkarni-mktg', '',
  80, '{"ai_depth": 20, "communication": 22, "experience_relevance": 19, "ambition": 19, "total": 80, "summary": "Strong marketing leader with real AI tool integration. Relevant brand-building experience."}',
  'shortlisted', 'form'
),

(
  'Tanvi Shah', 'tanvi.shah@gmail.com', '9478901234', 'Female',
  'Business Development Manager', 'Nykaa', 'product', 'E-commerce', 'Sales & Business Development',
  '4 years', 4, 'Loreal, Myntra',
  '18 LPA', 18, '26 LPA', 26,
  '1 month', 30,
  'Mumbai', 'Mumbai / Remote', 'hybrid', false,
  'MBA', 'SP Jain Mumbai', '2020', 'Tier 2',
  'B2B Sales, Brand Partnerships, Negotiation, CRM, Salesforce, Revenue Operations',
  'BD manager with strong brand partnership experience. Onboarded 200+ new brands to Nykaa marketplace.',
  '6', 'Claude for proposal writing, ChatGPT for research, Salesforce Einstein',
  'AI-assisted brand pitch decks reducing proposal creation time from 3 days to 4 hours.',
  'AI to qualify leads and personalise outreach. Focus human time on relationship and closing.',
  'Slower but fine. BD is fundamentally human.',
  'Signed ₹120Cr in brand partnerships at Nykaa over 2 years.',
  'Logistics brand partnerships are underdeveloped. Want to build that vertical at Shiprocket.',
  'https://linkedin.com/in/tanvishah-bd', '',
  58, '{"ai_depth": 13, "communication": 17, "experience_relevance": 15, "ambition": 13, "total": 58, "summary": "Decent BD background. Limited AI depth. Could work for seller success or partnerships roles."}',
  'new', 'form'
),

-- ============================================================
-- LOGISTICS COMPANIES
-- ============================================================

(
  'Vikrant Malhotra', 'vikrant.malhotra@gmail.com', '9367890123', 'Male',
  'Senior Operations Manager', 'Delhivery', 'logistics', 'Logistics', 'Operations',
  '7 years', 7, 'BlueDart, DTDC',
  '22 LPA', 22, '32 LPA', 32,
  '1 month', 30,
  'Delhi', 'Delhi NCR / Bengaluru', 'hybrid', true,
  'B.Tech + MBA', 'IIT Roorkee + ISB', '2017', 'Tier 1',
  'Supply Chain, Last-Mile Delivery, Route Optimisation, Warehouse Management, SLA Management, P&L',
  'Operations leader with 7 years across Delhivery, BlueDart. Deep last-mile expertise. Managed 150+ delivery partners.',
  '7', 'Claude for SOP documentation, Tableau AI, Excel Copilot, GPT for incident reports',
  'Built AI-assisted route optimisation system reducing average delivery TAT by 18% for Delhi NCR.',
  'AI for predictive SLA breach detection, automated exception handling, self-correcting routing.',
  'Would go back to manual SOPs and Excel. The horror.',
  'Delhivery Delhi operations — 50k daily shipments, 150 delivery partners, 98.2% SLA compliance.',
  'Shiprocket is building the category. Want to be part of that from the inside.',
  'https://linkedin.com/in/vikrantmalhotra-ops', '',
  72, '{"ai_depth": 17, "communication": 18, "experience_relevance": 22, "ambition": 15, "total": 72, "summary": "Strong logistics ops background. Practical AI usage. Very relevant experience for Shiprocket operations."}',
  'shortlisted', 'form'
),

(
  'Pooja Nair', 'pooja.nair@gmail.com', '9256789012', 'Female',
  'Product Manager — Tracking & Visibility', 'Ecom Express', 'logistics', 'Logistics', 'Product Management',
  '5 years', 5, 'Amazon Logistics, IndiGrid',
  '26 LPA', 26, '38 LPA', 38,
  '2 months', 60,
  'Bengaluru', 'Bengaluru', 'hybrid', false,
  'MBA', 'IIM Kozhikode', '2019', 'Tier 1',
  'Logistics Tech, Tracking Systems, B2B Product, API Integrations, SQL, Stakeholder Management',
  'PM specialising in logistics technology. Built real-time tracking platform at Ecom Express used by 5000+ merchant partners.',
  '8', 'Claude for PRDs and API specs, Postman AI, Figma AI, Notion AI',
  'Built AI-powered delay prediction model reducing customer complaints by 35% through proactive notifications.',
  'AI to predict and prevent exceptions before they happen. Zero-surprise logistics.',
  'Uncomfortable. AI is now central to how I think through problems.',
  'End-to-end shipment visibility platform at Ecom Express — real-time tracking, 5000+ merchants, 2M daily events.',
  'Shiprocket is the platform play in Indian logistics. Want to build the product layer here.',
  'https://linkedin.com/in/poojanair-pm-logistics', '',
  83, '{"ai_depth": 21, "communication": 21, "experience_relevance": 24, "ambition": 17, "total": 83, "summary": "Excellent profile — logistics PM with real AI integration. Very high experience relevance for Shiprocket."}',
  'interview', 'form'
),

(
  'Manish Gupta', 'manish.gupta@gmail.com', '9145678901', 'Male',
  'Data Analyst — Supply Chain', 'XpressBees', 'logistics', 'Logistics', 'Data Science & Analytics',
  '3 years', 3, 'Mahindra Logistics',
  '14 LPA', 14, '20 LPA', 20,
  'Immediate', 0,
  'Pune', 'Pune / Mumbai / Remote', 'hybrid', true,
  'B.Tech', 'COEP Pune', '2021', 'Tier 2',
  'Python, SQL, Power BI, Excel, Logistics Analytics, ETL, Route Analysis, Pandas',
  'Supply chain data analyst with logistics domain expertise. Built KPI dashboards tracking 30+ operational metrics at XpressBees.',
  '6', 'GitHub Copilot, Claude for query optimisation, ChatGPT for documentation',
  'Automated daily dispatch planning report using Python + AI, saving 2 hours of manual work daily.',
  'AI-assisted anomaly detection for shipment exceptions. Proactive not reactive operations.',
  'Would take longer but can work without.',
  'Network optimisation analysis reducing XpressBees Pune hub cost by 12% through lane consolidation.',
  'Want to scale my impact. Shiprocket data scale is 10x what I work with now.',
  'https://linkedin.com/in/manishgupta-scm', '',
  55, '{"ai_depth": 13, "communication": 14, "experience_relevance": 16, "ambition": 12, "total": 55, "summary": "Solid logistics analytics background. AI usage basic. Good entry-level data hire."}',
  'new', 'form'
),

(
  'Ankit Sharma', 'ankit.sharma@gmail.com', '9034567890', 'Male',
  'Software Engineer — Logistics Platform', 'Shadowfax', 'logistics', 'Logistics', 'Technology',
  '4 years', 4, 'NoBroker, Accenture',
  '20 LPA', 20, '30 LPA', 30,
  '1 month', 30,
  'Bengaluru', 'Bengaluru / Remote', 'remote', true,
  'B.Tech', 'NSIT Delhi', '2020', 'Tier 2',
  'Python, FastAPI, PostgreSQL, Redis, Kafka, Docker, GCP, Microservices, Routing Algorithms',
  'Backend engineer building logistics platform APIs at Shadowfax. Deep experience in order management and routing systems.',
  '7', 'GitHub Copilot, Claude for architecture discussions, ChatGPT for debugging',
  'Built intelligent order batching system using ML — 23% efficiency improvement in last-mile delivery.',
  'AI-generated routing rules, automated parameter tuning, predictive capacity planning.',
  'Would slow down significantly. Copilot is now muscle memory.',
  'Order assignment engine at Shadowfax — 500k daily shipments, real-time routing for 30k+ delivery partners.',
  'Shiprocket is building the AWS of Indian logistics. Want to work on the platform layer.',
  'https://linkedin.com/in/ankitsharma-logistics', 'https://github.com/ankit-dev',
  74, '{"ai_depth": 17, "communication": 18, "experience_relevance": 22, "ambition": 17, "total": 74, "summary": "Good logistics tech background. Practical AI usage. Strong experience relevance for Shiprocket engineering."}',
  'new', 'form'
),

(
  'Ritu Patel', 'ritu.patel@gmail.com', '8923456789', 'Female',
  'Category Manager', 'Porter', 'logistics', 'Logistics', 'Operations',
  '4 years 6 months', 4.5, 'Dunzo, BigBasket',
  '22 LPA', 22, '32 LPA', 32,
  '1 month', 30,
  'Mumbai', 'Mumbai / Remote', 'hybrid', false,
  'MBA', 'NMIMS Mumbai', '2020', 'Tier 2',
  'Category Management, Marketplace Operations, Pricing Strategy, Vendor Management, Excel, SQL',
  'Category manager with cross-logistics experience at Porter, Dunzo, BigBasket. Expert in hyperlocal supply-demand management.',
  '6', 'Claude for pricing analysis and reports, ChatGPT for supplier communication',
  'AI-assisted demand forecasting for Porter Mumbai reducing idle vehicle hours by 20%.',
  'AI to dynamically price and match supply in real-time without manual intervention.',
  'Slower but manageable.',
  'Built Porter Mumbai B2B category from scratch — ₹40Cr GMV in 18 months.',
  'Shiprocket seller ecosystem is untapped for category plays. Want to build that.',
  'https://linkedin.com/in/ritupatel-ops', '',
  63, '{"ai_depth": 14, "communication": 16, "experience_relevance": 18, "ambition": 15, "total": 63, "summary": "Good logistics operational background. Limited AI depth. Relevant for category or seller success roles."}',
  'new', 'form'
),

(
  'Deepak Verma', 'deepak.verma@gmail.com', '8812345678', 'Male',
  'Fleet & Network Manager', 'BlueDart', 'logistics', 'Logistics', 'Operations',
  '9 years', 9, 'DHL, FedEx India',
  '30 LPA', 30, '42 LPA', 42,
  '2 months', 60,
  'Mumbai', 'Mumbai / Pune', 'office', false,
  'B.Tech + MBA', 'NIT Nagpur + JBIMS', '2015', 'Tier 1',
  'Fleet Management, Route Optimisation, Cost Reduction, P&L, Vendor Negotiation, Transport Management System',
  'Logistics veteran with 9 years managing large-scale fleet operations. Led 2000+ vehicle network at BlueDart West India.',
  '5', 'Excel Copilot, GPT for vendor communication, some Power BI AI features',
  'Route optimisation using AI reducing fuel cost by ₹2Cr annually across West India network.',
  'Predictive maintenance, automated routing, AI-generated SOPs.',
  'Would be frustrating but manageable. Have 9 years of muscle memory.',
  'Integrated BlueDart West India hub network — 2000 vehicles, 15 cities, 98.5% on-time delivery.',
  'Shiprocket is disrupting incumbents like BlueDart. Want to be on the disrupting side.',
  'https://linkedin.com/in/deepakverma-fleet', '',
  61, '{"ai_depth": 12, "communication": 16, "experience_relevance": 20, "ambition": 13, "total": 61, "summary": "Strong logistics domain expertise. Low AI depth but very relevant operational experience."}',
  'new', 'form'
),

(
  'Keerthi Rajagopalan', 'keerthi.r@gmail.com', '8701234567', 'Female',
  'Product Manager — Seller Platform', 'Delhivery', 'logistics', 'Logistics', 'Product Management',
  '6 years', 6, 'FedEx India, WayCool',
  '32 LPA', 32, '45 LPA', 45,
  '2 months', 60,
  'Chennai', 'Bengaluru / Chennai / Remote', 'hybrid', true,
  'MBA', 'IIM Lucknow', '2018', 'Tier 1',
  'B2B Product, Logistics APIs, Seller Onboarding, Dashboard Design, SQL, Stakeholder Management',
  'Logistics PM with 6 years building seller-facing products. Led Delhivery seller portal used by 100k+ merchants.',
  '8', 'Claude for spec writing, Figma AI, SQL Copilot, Notion AI',
  'AI-generated dispute resolution workflow at Delhivery — auto-classifies complaints and routes to right team. 40% faster resolution.',
  'AI to predict seller churn and automatically trigger retention workflows.',
  'Uncomfortable. AI is now in every step of my product workflow.',
  'Delhivery merchant portal — 100k+ merchants, ₹1000Cr+ GMV facilitated, 45 product releases.',
  'Shiprocket seller platform is the most interesting product problem in Indian logistics right now.',
  'https://linkedin.com/in/keerthirajagopalan-pm', '',
  85, '{"ai_depth": 21, "communication": 22, "experience_relevance": 24, "ambition": 18, "total": 85, "summary": "Excellent logistics PM. High AI integration. Very high experience relevance. Strong hire for seller platform."}',
  'shortlisted', 'form'
),

(
  'Suresh Narayanan', 'suresh.n@gmail.com', '8590123456', 'Male',
  'Senior Data Engineer', 'DTDC', 'logistics', 'Logistics', 'Technology',
  '6 years', 6, 'Wipro, Cognizant',
  '22 LPA', 22, '34 LPA', 34,
  '1 month', 30,
  'Bengaluru', 'Bengaluru', 'hybrid', false,
  'B.Tech', 'Anna University', '2018', 'Tier 2',
  'Python, Spark, Airflow, Kafka, Snowflake, dbt, AWS Glue, Data Modelling, ETL',
  'Data engineer with logistics domain knowledge. Built real-time data pipelines at DTDC processing 5M+ daily events.',
  '6', 'GitHub Copilot, dbt Cloud AI, Claude for pipeline documentation',
  'Automated data quality monitoring using AI anomaly detection — catches 95% of data issues before they hit dashboards.',
  'AI-generated data models, automated pipeline optimisation, self-healing ETL.',
  'Functional but slower. Strong SQL fundamentals.',
  'Real-time logistics event streaming platform at DTDC — 5M daily events, sub-10s latency.',
  'Shiprocket data infrastructure is greenfield. Want to build the data platform.',
  'https://linkedin.com/in/sureshnarayanan-de', 'https://github.com/sureshdata',
  68, '{"ai_depth": 15, "communication": 17, "experience_relevance": 20, "ambition": 16, "total": 68, "summary": "Good data engineering skills with logistics context. Practical AI tool usage."}',
  'new', 'form'
),

-- ============================================================
-- MORE PRODUCT COMPANIES
-- ============================================================

(
  'Ishaan Trivedi', 'ishaan.trivedi@gmail.com', '8479012345', 'Male',
  'Senior Product Manager', 'Dream11', 'product', 'Gaming / Fantasy Sports', 'Product Management',
  '5 years', 5, 'Hotstar, Times Internet',
  '38 LPA', 38, '55 LPA', 55,
  '3 months', 90,
  'Mumbai', 'Mumbai / Remote', 'remote', true,
  'MBA', 'IIM Indore', '2019', 'Tier 1',
  'Consumer Product, Gamification, Personalisation, ML-powered features, SQL, Mobile Product',
  'PM at Dream11 owning core contest experience for 200M+ users. Expert in high-scale consumer product.',
  '9', 'Claude for product specs and strategy docs, Amplitude AI, Figma AI, custom GPT agents',
  'Built AI-powered team recommendation feature at Dream11 improving contest entry conversion by 31%.',
  'AI for real-time personalisation at scale — every user sees a different product based on their behaviour.',
  'Major workflow disruption. AI is in every step of my product thinking now.',
  'Core contest experience revamp at Dream11 — 200M users, 15M DAU, ₹2000Cr contest GMV.',
  'Consumer product at Shiprocket scale has never been seriously done. That challenge is compelling.',
  'https://linkedin.com/in/ishaantrivedi-pm', '',
  87, '{"ai_depth": 22, "communication": 22, "experience_relevance": 22, "ambition": 21, "total": 87, "summary": "Excellent consumer PM with proven AI-first product thinking. Strong hire for any consumer-facing role."}',
  'shortlisted', 'form'
),

(
  'Pallavi Desai', 'pallavi.desai@gmail.com', '8368901234', 'Female',
  'Senior SDE-II', 'Ola', 'product', 'Mobility', 'Technology',
  '6 years', 6, 'Uber, InMobi',
  '40 LPA', 40, '56 LPA', 56,
  '2 months', 60,
  'Bengaluru', 'Bengaluru / Remote', 'remote', true,
  'B.Tech', 'IIT Madras', '2018', 'Tier 1',
  'Java, Go, Distributed Systems, Real-time Systems, Kafka, Cassandra, System Design, AWS',
  'Senior engineer at Ola building real-time matching infrastructure. IIT Madras graduate with Uber experience.',
  '8', 'GitHub Copilot, Claude for system design review, DeepMind AlphaCode concepts for algorithms',
  'Built Ola real-time supply forecasting system reducing driver idle time by 25% in Bengaluru.',
  'AI to handle all boilerplate generation and test writing. Human focus on architecture and novel problems.',
  'Painful. Copilot is now as natural as typing.',
  'Ola real-time ride matching — 1M+ rides daily, sub-200ms matching latency.',
  'Real-time logistics systems are harder than ride matching. Want that complexity.',
  'https://linkedin.com/in/pallavidesai-sde', 'https://github.com/pallavi-dev',
  84, '{"ai_depth": 20, "communication": 21, "experience_relevance": 22, "ambition": 21, "total": 84, "summary": "Strong IIT engineer with real-time systems expertise. High AI integration. Excellent for platform engineering."}',
  'shortlisted', 'form'
),

(
  'Karan Mehta', 'karan.mehta@gmail.com', '8257890123', 'Male',
  'Growth Product Manager', 'ShareChat', 'product', 'Social Media', 'Product Management',
  '4 years', 4, 'InMobi, Times Internet',
  '28 LPA', 28, '40 LPA', 40,
  '1 month', 30,
  'Bengaluru', 'Bengaluru / Remote', 'hybrid', true,
  'MBA', 'MDI Gurgaon', '2020', 'Tier 1',
  'Growth Product, Virality, Retention, SQL, Mobile Analytics, A/B Testing, Push Notifications',
  'Growth PM at ShareChat driving user acquisition and retention for 200M users. Expert in vernacular content growth.',
  '7', 'Claude for experiment design and analysis, Amplitude AI, Mixpanel, AI copilot for SQL',
  'Built AI-driven notification personalisation system improving D7 retention by 18% at ShareChat.',
  'AI to run 100 experiments simultaneously. Growth becomes a data flywheel.',
  'Significantly slower. Experimentation velocity would collapse.',
  'ShareChat notification and onboarding system redesign — 15% D1 retention improvement, 200M users.',
  'Want to apply consumer growth thinking to a B2B platform. Different muscle.',
  'https://linkedin.com/in/karanmehta-growth', '',
  76, '{"ai_depth": 18, "communication": 19, "experience_relevance": 20, "ambition": 19, "total": 76, "summary": "Good growth PM with strong AI experimentation mindset. Consumer to B2B transition could be interesting."}',
  'new', 'form'
),

(
  'Neha Jain', 'neha.jain@gmail.com', '8146789012', 'Female',
  'Analytics Lead', 'PolicyBazaar', 'product', 'Insurtech', 'Data Science & Analytics',
  '7 years', 7, 'Gartner, EY',
  '35 LPA', 35, '48 LPA', 48,
  '2 months', 60,
  'Gurugram', 'Delhi NCR / Remote', 'remote', true,
  'MBA', 'FMS Delhi', '2017', 'Tier 1',
  'Python, SQL, Tableau, Machine Learning, Business Analytics, Attribution Modelling, Marketing Mix',
  'Analytics lead at PolicyBazaar with full P&L visibility. Built attribution and LTV models used for ₹500Cr+ marketing decisions.',
  '8', 'Claude for analysis summaries, Python Copilot, Tableau Pulse AI, custom analytics GPT',
  'Built AI-assisted marketing attribution model at PolicyBazaar improving ROAS accuracy by 40%.',
  'AI handles all descriptive analytics. I focus on causal inference and strategic decisions.',
  'Would still function. Strong statistical fundamentals from FMS.',
  'Marketing mix and LTV framework at PolicyBazaar — informs ₹500Cr+ annual marketing spend.',
  'Logistics analytics is 5 years behind fintech. Shiprocket can leapfrog with the right team.',
  'https://linkedin.com/in/nehajain-analytics', '',
  78, '{"ai_depth": 19, "communication": 20, "experience_relevance": 20, "ambition": 19, "total": 78, "summary": "Strong analytics leader with P&L context. Good AI depth for an analytics role. Would add strategic value."}',
  'new', 'form'
),

(
  'Akash Gupta', 'akash.gupta@gmail.com', '8035678901', 'Male',
  'Staff Engineer', 'MakeMyTrip', 'product', 'Travel Tech', 'Technology',
  '9 years', 9, 'Yatra, Goibibo',
  '55 LPA', 55, '75 LPA', 75,
  '3 months', 90,
  'Gurugram', 'Delhi NCR / Bengaluru', 'hybrid', false,
  'B.Tech', 'IIT Kharagpur', '2015', 'Tier 1',
  'Java, Scala, Distributed Systems, Search, Elasticsearch, Kafka, System Design, Team Leadership',
  'Staff engineer at MakeMyTrip leading search and recommendation systems. IIT Kharagpur background with 9 years building large-scale systems.',
  '7', 'GitHub Copilot, Claude for architecture review, AI-powered code review tools',
  'Rebuilt MakeMyTrip hotel search using ML-powered ranking, 25% improvement in booking conversion.',
  'AI code generation for non-critical paths. Human focus on system architecture and trade-offs.',
  'Slower but productive. Strong CS fundamentals from IIT.',
  'Hotel search and ranking system at MakeMyTrip — 50M monthly searches, 12% booking conversion.',
  'Logistics search and matching systems are harder than travel. Want that challenge.',
  'https://linkedin.com/in/akashgupta-staff', 'https://github.com/akashg',
  79, '{"ai_depth": 17, "communication": 19, "experience_relevance": 22, "ambition": 21, "total": 79, "summary": "Experienced staff engineer with search systems background. Relevant for Shiprocket platform."}',
  'new', 'form'
),

(
  'Ritika Malhotra', 'ritika.malhotra@gmail.com', '7924567890', 'Female',
  'Product Designer', 'Zepto', 'product', 'Quick Commerce', 'Design',
  '3 years', 3, 'Dunzo, OYO',
  '18 LPA', 18, '26 LPA', 26,
  '15 days', 15,
  'Mumbai', 'Mumbai / Remote', 'remote', true,
  'B.Des', 'Symbiosis Design', '2021', 'Tier 2',
  'Figma, User Research, Prototyping, Mobile Design, Design Systems, Motion, Usability Testing',
  'Product designer at Zepto with quick commerce expertise. Owns consumer app design for 3M+ orders/month.',
  '8', 'Figma AI, Midjourney for concepts, Claude for copy and content design, Protopie AI',
  'Redesigned Zepto checkout flow using AI-synthesised usability insights. 28% drop in cart abandonment.',
  'AI for rapid concept generation and user research synthesis. 5x faster design iterations.',
  'Would feel significantly slower. AI is in my daily design process.',
  'Zepto app redesign from scratch — 3M orders/month, consumer NPS improved by 22 points.',
  'Logistics app design is terrible industry-wide. Shiprocket has real design debt to fix.',
  'https://linkedin.com/in/ritikmalhotra-design', '',
  72, '{"ai_depth": 19, "communication": 18, "experience_relevance": 17, "ambition": 18, "total": 72, "summary": "Good designer with AI-first workflow. Quick commerce experience relevant for last-mile consumer products."}',
  'new', 'form'
),

(
  'Vivek Srinivasan', 'vivek.s@gmail.com', '7813456789', 'Male',
  'Principal Product Manager', 'Juspay', 'product', 'Fintech', 'Product Management',
  '8 years', 8, 'Citrus Pay, Mobikwik, PayU',
  '55 LPA', 55, '70 LPA', 70,
  '3 months', 90,
  'Bengaluru', 'Bengaluru', 'hybrid', false,
  'M.Tech', 'IIT Madras', '2016', 'Tier 1',
  'Payments Product, APIs, B2B SaaS, Developer Experience, SDK Design, Revenue Growth',
  'Principal PM at Juspay with deep payments infrastructure expertise. Has led products used by Swiggy, Zomato, Amazon India.',
  '8', 'Claude for technical product specs and API design, Postman AI, Figma AI',
  'AI-powered payment failure prediction at Juspay reducing false declines by 22% across 500M+ monthly transactions.',
  'AI to auto-generate API documentation, SDK changelogs, integration guides. Dev experience on autopilot.',
  'Major productivity hit. Spec writing and technical analysis are heavily AI-assisted now.',
  'Juspay Hypercheckout — now used by 50+ enterprise clients including Swiggy, Amazon, Flipkart.',
  'Payments + logistics is the next frontier. Shiprocket can be the infrastructure layer for D2C commerce.',
  'https://linkedin.com/in/viveksrinivasan-pm', '',
  85, '{"ai_depth": 21, "communication": 22, "experience_relevance": 22, "ambition": 20, "total": 85, "summary": "Excellent fintech PM with infrastructure product depth. High AI integration. Strong strategic thinking."}',
  'shortlisted', 'form'
),

(
  'Harsha Vardhan', 'harsha.v@gmail.com', '7702345678', 'Male',
  'Engineering Manager', 'Freshworks', 'product', 'SaaS', 'Technology',
  '9 years', 9, 'Zoho, Oracle',
  '48 LPA', 48, '65 LPA', 65,
  '3 months', 90,
  'Chennai', 'Chennai / Remote', 'hybrid', false,
  'B.Tech', 'NIT Trichy', '2015', 'Tier 1',
  'Python, Django, React, System Design, Team Leadership, B2B SaaS, Multi-tenancy',
  'EM at Freshworks leading CRM product engineering. 7-person team, strong SaaS architecture background.',
  '7', 'GitHub Copilot, Claude for engineering design reviews, Linear AI, Sentry AI for debugging',
  'Built AI-powered ticket auto-assignment at Freshworks using Claude API. 65% of tickets auto-resolved.',
  'AI to handle all tier-1 support automation. Human engineers focus on complex integrations and new features.',
  'Productivity will take a hit. But the fundamentals are strong.',
  'Freshworks CRM bulk actions and workflow automation — used by 60k+ businesses worldwide.',
  'B2B SaaS thinking applied to logistics platform is rare. That combination is what Shiprocket needs.',
  'https://linkedin.com/in/harshavardhan-em', 'https://github.com/harsha-fresh',
  76, '{"ai_depth": 17, "communication": 19, "experience_relevance": 21, "ambition": 19, "total": 76, "summary": "Solid SaaS engineering leader. Practical AI integration. B2B platform experience relevant."}',
  'new', 'form'
),

(
  'Meera Krishnan', 'meera.krishnan@gmail.com', '7591234567', 'Female',
  'Head of Data Science', 'Lenskart', 'product', 'D2C / Retail', 'Data Science & Analytics',
  '10 years', 10, 'Walmart Labs, Target',
  '65 LPA', 65, '85 LPA', 85,
  '3 months', 90,
  'Bengaluru', 'Bengaluru', 'hybrid', false,
  'MS', 'ISI Kolkata', '2014', 'Tier 1',
  'Machine Learning, Deep Learning, Computer Vision, NLP, MLOps, Team Leadership, Python',
  'Data science leader with 10 years and retail domain depth. Built Lenskart recommendation and personalisation systems.',
  '9', 'Claude API for data product specs, Weights & Biases, Cursor for ML code, H2O AutoML',
  'Lenskart virtual try-on using computer vision — 40% improvement in online conversion, 4M uses/month.',
  'AI agents for end-to-end ML pipelines. Team of data scientists focuses on novel problems only.',
  'Painful. The entire ML workflow is AI-augmented now.',
  'Computer vision platform at Lenskart from scratch — serving 4M AR try-ons/month.',
  'Logistics has massive untapped ML potential — demand sensing, dynamic routing, fraud detection. All underdone.',
  'https://linkedin.com/in/meera-ds-head', '',
  88, '{"ai_depth": 23, "communication": 21, "experience_relevance": 23, "ambition": 21, "total": 88, "summary": "Exceptional data science leader. Deep AI expertise with leadership experience. Top-tier candidate."}',
  'interview', 'form'
);
