import Link from "next/link";
import type { ReactNode } from "react";
import {
  HYR,
  type AiInterviewRow,
  type CompetencyResult,
  type IntegritySummary,
  type InterviewReport,
} from "@/lib/interview-types";
import PrintButton from "./print-button";

/*
 * Renders the Reqr "Interview Results" branded assessment as a scrollable web
 * document that also prints 1:1 to US Letter (see report.css). Pure server
 * component — the only client code is the PrintButton in the toolbar.
 *
 * Pagination: each <section class="report-page"> is one printed page
 * (break-after: page). Section count is fixed per report: cover, scorecard,
 * one deep-dive page per group of 3 competencies (role fit + risk calibration
 * ride on the last one), and the final recommendation — so footers carry
 * static "Page N of M" numbers.
 */

const score10 = (n: number) => `${n.toFixed(1)}/10`;
const pct = (n: number) => `${Math.round(n)}%`;
const isWarnTier = (tier: CompetencyResult["tier"]) =>
  tier === "Developing" || tier === "Weak";

function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

// ── Shared fragments ────────────────────────────────────────────────────────

function RunningHeader() {
  return (
    <div className="hyr-run-head">
      <span className="hyr-run-brand">Reqr Interview Results</span>
      <span className="hyr-run-type">Candidate Assessment</span>
    </div>
  );
}

function PageFooter({ page, total }: { page: number; total: number }) {
  return (
    <div className="hyr-page-footer">
      Generated by Reqr &nbsp;|&nbsp; Confidential &nbsp;|&nbsp; Page {page} of {total}
    </div>
  );
}

function H2({ children }: { children: ReactNode }) {
  return <h2 className="hyr-h2">{children}</h2>;
}

/** 126px score ring — solid banner-green progress on a mint track. */
function Donut({ percent }: { percent: number }) {
  const size = 126;
  const stroke = 12;
  const r = (size - stroke) / 2;
  const c = 2 * Math.PI * r;
  const clamped = Math.max(0, Math.min(100, percent));
  const dash = (clamped / 100) * c;
  return (
    <svg
      width={size}
      height={size}
      viewBox={`0 0 ${size} ${size}`}
      role="img"
      aria-label={`Overall score ${pct(percent)}`}
    >
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke={HYR.mint} strokeWidth={stroke} />
      <circle
        cx={size / 2}
        cy={size / 2}
        r={r}
        fill="none"
        stroke={HYR.banner}
        strokeWidth={stroke}
        strokeDasharray={`${dash} ${c - dash}`}
        transform={`rotate(-90 ${size / 2} ${size / 2})`}
      />
      <text
        x={size / 2}
        y={size / 2}
        textAnchor="middle"
        dominantBaseline="central"
        fontSize={27}
        fontWeight={700}
        fill={HYR.primaryDark}
      >
        {pct(percent)}
      </text>
    </svg>
  );
}

// ── Page 1: cover ───────────────────────────────────────────────────────────

function CoverPage({
  row,
  report,
  page,
  total,
}: {
  row: AiInterviewRow;
  report: InterviewReport;
  page: number;
  total: number;
}) {
  return (
    <section className="report-page">
      <RunningHeader />

      <div className="hyr-hero">
        <h1>Reqr Interview Results</h1>
        <p>Detailed Candidate Assessment Report</p>
      </div>

      <div className="hyr-panel-card avoid-break">
        <div className="hyr-panel hyr-panel-main">
          <div className="hyr-label">Candidate</div>
          <h2 className="hyr-candidate-name">{row.candidate_name}</h2>
          <p className="hyr-meta-line">
            <strong>Position applied:</strong> {row.role_title}
          </p>
          {row.candidate_email ? (
            <p className="hyr-meta-line">
              <strong>Email:</strong> {row.candidate_email}
            </p>
          ) : null}
          <p className="hyr-meta-line">
            <strong>Interview stage:</strong> {report.interview_stage}
          </p>
        </div>
        <div className="hyr-panel-divider" />
        <div className="hyr-panel hyr-panel-score">
          <Donut percent={report.overall_percent} />
          <div className="hyr-label hyr-donut-caption">{report.interview_stage}</div>
          <div className="hyr-panel-verdict">{report.verdict}</div>
        </div>
      </div>

      <H2>Executive Summary</H2>
      <p className="hyr-para">{report.executive_summary[0]}</p>
      <p className="hyr-para">{report.executive_summary[1]}</p>

      <div className="hyr-stat-strip avoid-break">
        {report.summary_stats.map((s) => (
          <div key={s.label}>
            <div className="hyr-label">{s.label}</div>
            <div className="hyr-stat-score">{score10(s.score)}</div>
            <div className="hyr-stat-caption">{s.caption}</div>
          </div>
        ))}
      </div>

      <div className="hyr-conclusion avoid-break">
        <div className="hyr-label">{report.hiring_conclusion.label}</div>
        <p>{report.hiring_conclusion.text}</p>
      </div>

      <PageFooter page={page} total={total} />
    </section>
  );
}

// ── Page 2: scorecard ───────────────────────────────────────────────────────

function ScorecardPage({
  report,
  page,
  total,
}: {
  report: InterviewReport;
  page: number;
  total: number;
}) {
  return (
    <section className="report-page">
      <RunningHeader />

      <H2>Competency Scorecard</H2>
      <table className="hyr-table">
        <thead>
          <tr>
            <th>Competency</th>
            <th className="col-score">Score</th>
            <th className="col-tier">Assessment</th>
          </tr>
        </thead>
        <tbody>
          {report.competencies.map((c) => (
            <tr key={c.name}>
              <td>{c.name}</td>
              <td className="hyr-score-cell">{score10(c.score)}</td>
              <td className={`hyr-tier-cell${isWarnTier(c.tier) ? " is-warn" : ""}`}>
                {c.tier}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <H2>Evidence of Business Impact</H2>
      <div className="hyr-impact-grid avoid-break">
        {report.business_impact.map((t) => (
          <div key={t.label} className="hyr-impact-card">
            <div className="hyr-label">{t.label}</div>
            <div className="hyr-impact-value">{t.value}</div>
            <div className="hyr-stat-caption">{t.caption}</div>
          </div>
        ))}
      </div>

      <H2>Hiring Committee Snapshot</H2>
      <div className="hyr-snapshot avoid-break">
        <div className="hyr-snap-box hyr-snap-strengths">
          <div className="hyr-label">Primary Strengths</div>
          <ul className="hyr-ul">
            {report.strengths.map((s) => (
              <li key={s}>{s}</li>
            ))}
          </ul>
        </div>
        <div className="hyr-snap-box hyr-snap-watch">
          <div className="hyr-label">Watch Areas</div>
          <ul className="hyr-ul">
            {report.watch_areas.map((s) => (
              <li key={s}>{s}</li>
            ))}
          </ul>
        </div>
      </div>

      <p className="hyr-note">
        <strong>Assessment note:</strong> {report.assessment_note}
      </p>

      <PageFooter page={page} total={total} />
    </section>
  );
}

// ── Interview integrity ─────────────────────────────────────────────────────

function formatSeconds(seconds: number): string {
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  const remainder = seconds % 60;
  return remainder ? `${minutes}m ${remainder}s` : `${minutes}m`;
}

function IntegrityPage({
  integrity,
  contentPercent,
  adjustment,
  overallPercent,
  page,
  total,
}: {
  integrity: IntegritySummary;
  contentPercent: number;
  adjustment: number;
  overallPercent: number;
  page: number;
  total: number;
}) {
  const signals = [
    { label: "Tab switches", value: integrity.tab_switches },
    { label: "Window switches", value: integrity.window_switches },
    { label: "Fullscreen exits", value: integrity.fullscreen_exits },
    { label: "Long breaks", value: integrity.long_breaks },
  ];

  return (
    <section className="report-page">
      <RunningHeader />
      <H2>Interview Integrity</H2>

      <div className="hyr-integrity-hero avoid-break">
        <div>
          <div className="hyr-label">Integrity score</div>
          <div className="hyr-integrity-score">{integrity.score}/100</div>
        </div>
        <div>
          <div className="hyr-label">Signal risk</div>
          <div className={`hyr-integrity-risk${integrity.risk_level === "LOW" ? "" : " is-warn"}`}>
            {integrity.risk_level}
          </div>
        </div>
        <div>
          <div className="hyr-label">Longest time away</div>
          <div className="hyr-integrity-duration">
            {formatSeconds(integrity.longest_away_seconds)}
          </div>
        </div>
      </div>

      <div className="hyr-integrity-grid avoid-break">
        {signals.map((signal) => (
          <div key={signal.label}>
            <div className="hyr-label">{signal.label}</div>
            <div className="hyr-integrity-count">{signal.value}</div>
          </div>
        ))}
      </div>

      <H2>Recorded Observations</H2>
      <ul className="hyr-ul">
        {integrity.observations.map((observation) => (
          <li key={observation}>{observation}</li>
        ))}
      </ul>

      <H2>Overall Score Impact</H2>
      <div className="hyr-score-impact avoid-break">
        <div>
          <span>Job-fit assessment</span>
          <strong>{contentPercent}%</strong>
        </div>
        <div>
          <span>Capped integrity adjustment</span>
          <strong>{adjustment} points</strong>
        </div>
        <div>
          <span>Final overall score</span>
          <strong>{overallPercent}%</strong>
        </div>
      </div>
      <p className="hyr-note">
        Focus and break signals provide review context; they do not by themselves prove misconduct.
        The adjustment is deterministic and capped at 20 points.
      </p>

      <PageFooter page={page} total={total} />
    </section>
  );
}

// ── Pages 3–5: competency deep-dive ─────────────────────────────────────────

function CompetencyCard({ comp, number }: { comp: CompetencyResult; number: number }) {
  return (
    <div className="hyr-comp avoid-break">
      <div className="hyr-comp-head">
        <span className="hyr-comp-num">{number}</span>
        <span className="hyr-comp-name">{comp.name}</span>
      </div>
      <div className="hyr-comp-body">
        <div className="hyr-comp-main">
          <p>{comp.narrative}</p>
          <ul className="hyr-ul">
            {comp.evidence.map((e) => (
              <li key={e}>{e}</li>
            ))}
          </ul>
          <p className="hyr-observation">
            <strong>Hiring observation:</strong> <em>{comp.observation}</em>
          </p>
        </div>
        <div className="hyr-comp-side">
          <div className="hyr-comp-score">{score10(comp.score)}</div>
          <div className={`hyr-comp-tier${isWarnTier(comp.tier) ? " is-warn" : ""}`}>
            {comp.tier}
          </div>
        </div>
      </div>
    </div>
  );
}

function DeepDivePage({
  comps,
  startNumber,
  roleTitle,
  roleFit,
  riskCalibration,
  page,
  total,
}: {
  comps: CompetencyResult[];
  startNumber: number;
  roleTitle: string;
  roleFit: InterviewReport["role_fit"];
  riskCalibration: InterviewReport["risk_calibration"];
  page: number;
  total: number;
}) {
  return (
    <section className="report-page">
      <RunningHeader />

      {comps.map((c, i) => (
        <CompetencyCard key={c.name} comp={c} number={startNumber + i} />
      ))}

      {roleFit ? (
        <>
          <H2>The {roleTitle} Role Fit</H2>
          <div className="hyr-fit-grid avoid-break">
            <div className="hyr-fit-cell">
              <div className="hyr-label hyr-label-primary">Strongest Match</div>
              <p className="hyr-fit-text">{roleFit.strongest_match}</p>
            </div>
            <div className="hyr-fit-cell">
              <div className="hyr-label hyr-label-primary">Environment Fit</div>
              <p className="hyr-fit-text">{roleFit.environment_fit}</p>
            </div>
            <div className="hyr-fit-cell">
              <div className="hyr-label hyr-label-primary">Role Risk</div>
              <p className="hyr-fit-text">{roleFit.role_risk}</p>
            </div>
            <div className="hyr-fit-cell">
              <div className="hyr-label hyr-label-primary">Level Calibration</div>
              <p className="hyr-fit-text">{roleFit.level_calibration}</p>
            </div>
          </div>
        </>
      ) : null}

      {riskCalibration && riskCalibration.length > 0 ? (
        <>
          <H2>Risk Calibration</H2>
          <div className="hyr-risk-row avoid-break">
            {riskCalibration.map((r) => (
              <div key={r.label}>
                <div className="hyr-label">{r.label}</div>
                <div className={`hyr-risk-level${r.level === "LOW" ? "" : " is-warn"}`}>
                  {r.level}
                </div>
              </div>
            ))}
          </div>
        </>
      ) : null}

      <PageFooter page={page} total={total} />
    </section>
  );
}

// ── Page 6: final hiring recommendation ─────────────────────────────────────

function FinalPage({
  report,
  page,
  total,
}: {
  report: InterviewReport;
  page: number;
  total: number;
}) {
  return (
    <section className="report-page">
      <RunningHeader />

      <div className="hyr-hero">
        <h1>Final Hiring Recommendation</h1>
        <p>Decision summary for the hiring team</p>
      </div>

      <div className="hyr-panel-card avoid-break">
        <div className="hyr-panel hyr-panel-main">
          <div className="hyr-label">Recommendation</div>
          <div
            className={`hyr-verdict ${
              report.verdict.length <= 15 ? "hyr-verdict-lg" : "hyr-verdict-sm"
            }`}
          >
            {report.verdict}
          </div>
          <p>{report.hiring_conclusion.text}</p>
        </div>
        <div className="hyr-panel-divider" />
        <div className="hyr-panel hyr-panel-score">
          <div className="hyr-final-percent">{pct(report.overall_percent)}</div>
          <div className="hyr-label hyr-donut-caption">{report.interview_stage}</div>
        </div>
      </div>

      <H2>Why This Candidate Should Progress</H2>
      <ul className="hyr-ul">
        {report.why_progress.map((w) => (
          <li key={w}>{w}</li>
        ))}
      </ul>

      <H2>Recommended Final-Round Focus</H2>
      <div className="hyr-fit-grid avoid-break">
        {report.final_round_focus.map((f) => (
          <div key={f.label} className="hyr-fit-cell">
            <div className="hyr-focus-label">{f.label}</div>
            <p className="hyr-fit-text">{f.text}</p>
          </div>
        ))}
      </div>

      <H2>Final Assessment</H2>
      <p className="hyr-para">{report.final_assessment[0]}</p>
      <p className="hyr-para">{report.final_assessment[1]}</p>

      <PageFooter page={page} total={total} />
    </section>
  );
}

// ── Document ────────────────────────────────────────────────────────────────

export default function ReportView({
  row,
  report,
  recordingUrl,
}: {
  row: AiInterviewRow;
  report: InterviewReport;
  recordingUrl: string | null;
}) {
  const compPages = chunk(report.competencies, 3);
  const totalPages = 3 + compPages.length + (report.integrity ? 1 : 0);
  const positive =
    report.verdict === "STRONG HIRE" || report.verdict === "RECOMMENDED TO PROGRESS";

  return (
    <>
      {/* Screen-only toolbar — hidden entirely when printing */}
      <header className="screen-only sticky top-0 z-20 border-b border-zinc-200 bg-white/95 backdrop-blur">
        <div className="mx-auto flex max-w-[850px] items-center justify-between gap-3 px-4 py-3 font-sans">
          <Link
            href="/employer/dashboard?tab=ai"
            className="shrink-0 text-sm font-medium text-zinc-600 transition-colors hover:text-zinc-900"
          >
            &larr; Back to dashboard
          </Link>
          <div className="flex min-w-0 items-center gap-2">
            <span className="truncate text-sm font-semibold text-zinc-900">
              {row.candidate_name}
            </span>
            <span
              className="shrink-0 rounded-sm px-2 py-0.5 text-[11px] font-bold tracking-wide"
              style={
                positive
                  ? { background: HYR.mint, color: HYR.primaryDark }
                  : { background: HYR.cream, color: HYR.amber }
              }
            >
              {report.verdict}
            </span>
          </div>
          <div className="flex shrink-0 items-center gap-2">
            {recordingUrl ? (
              <a
                href={recordingUrl}
                target="_blank"
                rel="noreferrer"
                className="rounded border border-zinc-300 px-3 py-1.5 text-xs font-semibold text-zinc-700 transition-colors hover:bg-zinc-50"
              >
                Watch recording
              </a>
            ) : null}
            <PrintButton />
          </div>
        </div>
      </header>

      <main className="hyr-doc mx-auto max-w-[850px] px-4 py-8">
        <CoverPage row={row} report={report} page={1} total={totalPages} />
        <ScorecardPage report={report} page={2} total={totalPages} />
        {compPages.map((comps, i) => {
          const last = i === compPages.length - 1;
          return (
            <DeepDivePage
              key={comps[0]?.name ?? i}
              comps={comps}
              startNumber={i * 3 + 1}
              roleTitle={row.role_title}
              roleFit={last ? report.role_fit : null}
              riskCalibration={last ? report.risk_calibration : null}
              page={3 + i}
              total={totalPages}
            />
          );
        })}
        {report.integrity ? (
          <IntegrityPage
            integrity={report.integrity}
            contentPercent={report.content_percent ?? report.overall_percent}
            adjustment={report.integrity_adjustment ?? 0}
            overallPercent={report.overall_percent}
            page={3 + compPages.length}
            total={totalPages}
          />
        ) : null}
        <FinalPage report={report} page={totalPages} total={totalPages} />
      </main>
    </>
  );
}
